return {
    wood = {
        name = "Wood",
        type = "Material",
        rarity = "Common",
        weight = 1,
        sellPrice = 3,
        strongPower = 0,
        survivability = 0,
        looting = 0,
        description = "A basic crafting material gathered from trees.",
    },
    stone = {
        name = "Stone",
        type = "Material",
        rarity = "Common",
        weight = 2,
        sellPrice = 2,
        strongPower = 0,
        survivability = 0,
        looting = 0,
        description = "A sturdy material used to make simple tools.",
    },
    fiber = {
        name = "Fiber",
        type = "Material",
        rarity = "Common",
        weight = 0.2,
        sellPrice = 1,
        strongPower = 0,
        survivability = 0,
        looting = 0,
        description = "Plant fibers that can be woven or tied together.",
    },
    iron_bar = {
        name = "Iron Bar",
        type = "Material",
        rarity = "Common",
        weight = 2,
        sellPrice = 8,
        strongPower = 0,
        survivability = 0,
        looting = 0,
        description = "A metal bar ready to be shaped into equipment.",
    },
    steel_sword = {
        name = "Steel Sword",
        type = "Weapon",
        rarity = "Uncommon",
        weight = 4,
        sellPrice = 25,
        equipmentSlot = "weapon",
        strongPower = 5,
        survivability = 0,
        looting = 0,
        description = "A sturdy sword with a wooden handle.",
    },
    rope = {
        name = "Rope",
        type = "Tool",
        rarity = "Common",
        weight = 1,
        sellPrice = 4,
        strongPower = 0,
        survivability = 0,
        looting = 0,
        description = "A strong rope made from twisted fibers.",
    },
    leather_helmet = {
        name = "Leather Helmet", type = "Head Armor", rarity = "Common",
        weight = 1, sellPrice = 7, equipmentSlot = "helmet",
        strongPower = 0, survivability = 2, looting = 0,
        description = "Simple protection for your head.",
    },
    leather_chestplate = {
        name = "Leather Chestplate", type = "Chest Armor", rarity = "Common",
        weight = 3, sellPrice = 12, equipmentSlot = "chestplate",
        strongPower = 0, survivability = 3, looting = 0,
        description = "A fitted leather chestplate.",
    },
    leather_gloves = {
        name = "Leather Gloves", type = "Hand Armor", rarity = "Common",
        weight = 1, sellPrice = 5, equipmentSlot = "gloves",
        strongPower = 0, survivability = 1, looting = 1,
        description = "Gloves that make it easier to gather supplies.",
    },
    leather_leggings = {
        name = "Leather Leggings", type = "Leg Armor", rarity = "Common",
        weight = 2, sellPrice = 8, equipmentSlot = "leggings",
        strongPower = 0, survivability = 2, looting = 0,
        description = "Flexible protection for your legs.",
    },
    leather_boots = {
        name = "Leather Boots", type = "Foot Armor", rarity = "Common",
        weight = 1, sellPrice = 6, equipmentSlot = "boots",
        strongPower = 0, survivability = 1, looting = 1,
        description = "Sturdy boots for a long expedition.",
    },
    rusty_sword = {
        name = "Rusty Sword", type = "Weapon", rarity = "Common",
        weight = 3, sellPrice = 10, equipmentSlot = "weapon",
        strongPower = 2, survivability = 0, looting = 0,
        description = "An old sword that still works.",
    },
    healing_potion = {
        name = "Healing Potion", type = "Consumable", rarity = "Common",
        weight = 0.5, sellPrice = 5, equipmentSlot = "consumable",
        strongPower = 0, survivability = 1, looting = 0,
        description = "A small potion packed for the night expedition.",
    },
}
